### ISSUE TITLE
Registration page border not properly sizing (Frontend)

### ISSUE THREAD

**Issue by Kcam9908** [dseeler/CSCI4050-Bookstore#5]
When trying to add a colored border, the registration page does not properly size. The form is not being included in the "container" class for some reason. Might be something to do with Django's auto form making.

**Comment by dseeler** [comment]
I noticed that Django forms are a little weird myself. Try removing the <ul> tags surrounding the form. Also, inspect the page source and see if the form is actually with the container

**Comment by dseeler** [comment]
I noticed that Django forms are a little weird myself. Try removing the tags surrounding the form. Also, inspect the page source and see if the form is actually with the container

**Comment by dseeler** [comment]
Worst case scenario, you can pick apart the elements of the form (ie {{ form.username }})instead of using the whole pregenerated one
